AllCops:
  TargetRubyVersion: 4.0
  NewCops: enable
  SuggestExtensions: false

# 行の長さ（デフォルト: 120）
Layout/LineLength:
  Max: 160
  AllowedPatterns:
    # コメント行は除外
    - '\A\s*#'

# ハッシュの値を開き括弧の直後ではなく次の行から揃える
Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

# メソッド引数を開き括弧の直後ではなく次の行から揃える
Layout/FirstArgumentIndentation:
  EnforcedStyle: consistent

# 複数行の引数は最初の引数に揃えるのではなくインデントで揃える
Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

# メソッドチェーンは直前の行頭からインデントする
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

# メトリクスに関するフォーマットは無効にする
Metrics:
  Enabled: false

# ドキュメントコメントの必須を無効化
Style/Documentation:
  Enabled: false

# frozen_string_literalのコメント必須を無効化
Style/FrozenStringLiteralComment:
  Enabled: true

# 文字列についてシングルクオート強制を無効化
Style/StringLiterals:
  Enabled: false

# メソッドの引数名は最低三文字以上でなくてもいい
Naming/MethodParameterName:
  Enabled: false
